#!/usr/bin/env python3

import json
import subprocess


result = subprocess.run(
    ["cargo", "metadata", "--no-deps", "--format-version=1"],
    stdin=subprocess.DEVNULL,
    capture_output=True,
    check=True,
    encoding="UTF-8",
)
data = json.loads(result.stdout)
print(data["target_directory"])
